// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: problem.proto

package jjudgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Problem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty     int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TimeLimit      int64                  `protobuf:"varint,5,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MemoryLimit    int64                  `protobuf:"varint,6,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	TestcaseBundle *TestcaseBundle        `protobuf:"bytes,7,opt,name=testcase_bundle,json=testcaseBundle,proto3" json:"testcase_bundle,omitempty"`
	Tags           []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Problem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Problem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Problem) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Problem) GetTimeLimit() int64 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *Problem) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Problem) GetTestcaseBundle() *TestcaseBundle {
	if x != nil {
		return x.TestcaseBundle
	}
	return nil
}

func (x *Problem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Problem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Problem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TestcaseBundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey      string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Sha256         string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	TestcaseGroups []*TestcaseGroup       `protobuf:"bytes,3,rep,name=testcase_groups,json=testcaseGroups,proto3" json:"testcase_groups,omitempty"`
	Version        int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestcaseBundle) Reset() {
	*x = TestcaseBundle{}
	mi := &file_problem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestcaseBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestcaseBundle) ProtoMessage() {}

func (x *TestcaseBundle) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestcaseBundle.ProtoReflect.Descriptor instead.
func (*TestcaseBundle) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{1}
}

func (x *TestcaseBundle) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *TestcaseBundle) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *TestcaseBundle) GetTestcaseGroups() []*TestcaseGroup {
	if x != nil {
		return x.TestcaseGroups
	}
	return nil
}

func (x *TestcaseBundle) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TestcaseGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ordinal       int32                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	ProblemId     int64                  `protobuf:"varint,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Testcases     []*Testcase            `protobuf:"bytes,5,rep,name=testcases,proto3" json:"testcases,omitempty"`
	Points        int32                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestcaseGroup) Reset() {
	*x = TestcaseGroup{}
	mi := &file_problem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestcaseGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestcaseGroup) ProtoMessage() {}

func (x *TestcaseGroup) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestcaseGroup.ProtoReflect.Descriptor instead.
func (*TestcaseGroup) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{2}
}

func (x *TestcaseGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestcaseGroup) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *TestcaseGroup) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *TestcaseGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestcaseGroup) GetTestcases() []*Testcase {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *TestcaseGroup) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type Testcase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ordinal         int32                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	TestcaseGroupId int64                  `protobuf:"varint,3,opt,name=testcase_group_id,json=testcaseGroupId,proto3" json:"testcase_group_id,omitempty"`
	Input           string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output          string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	InKey           string                 `protobuf:"bytes,6,opt,name=in_key,json=inKey,proto3" json:"in_key,omitempty"`
	OutKey          string                 `protobuf:"bytes,7,opt,name=out_key,json=outKey,proto3" json:"out_key,omitempty"`
	IsHidden        bool                   `protobuf:"varint,8,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Testcase) Reset() {
	*x = Testcase{}
	mi := &file_problem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Testcase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Testcase) ProtoMessage() {}

func (x *Testcase) ProtoReflect() protoreflect.Message {
	mi := &file_problem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Testcase.ProtoReflect.Descriptor instead.
func (*Testcase) Descriptor() ([]byte, []int) {
	return file_problem_proto_rawDescGZIP(), []int{3}
}

func (x *Testcase) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Testcase) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Testcase) GetTestcaseGroupId() int64 {
	if x != nil {
		return x.TestcaseGroupId
	}
	return 0
}

func (x *Testcase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Testcase) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Testcase) GetInKey() string {
	if x != nil {
		return x.InKey
	}
	return ""
}

func (x *Testcase) GetOutKey() string {
	if x != nil {
		return x.OutKey
	}
	return ""
}

func (x *Testcase) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

var File_problem_proto protoreflect.FileDescriptor

const file_problem_proto_rawDesc = "" +
	"\n" +
	"\rproblem.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\aProblem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x05 \x01(\x03R\ttimeLimit\x12!\n" +
	"\fmemory_limit\x18\x06 \x01(\x03R\vmemoryLimit\x12<\n" +
	"\x0ftestcase_bundle\x18\a \x01(\v2\x13.api.TestcaseBundleR\x0etestcaseBundle\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9e\x01\n" +
	"\x0eTestcaseBundle\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12;\n" +
	"\x0ftestcase_groups\x18\x03 \x03(\v2\x12.api.TestcaseGroupR\x0etestcaseGroups\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"\xb1\x01\n" +
	"\rTestcaseGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x05R\aordinal\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x03 \x01(\x03R\tproblemId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12+\n" +
	"\ttestcases\x18\x05 \x03(\v2\r.api.TestcaseR\ttestcases\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x05R\x06points\"\xdb\x01\n" +
	"\bTestcase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x05R\aordinal\x12*\n" +
	"\x11testcase_group_id\x18\x03 \x01(\x03R\x0ftestcaseGroupId\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x15\n" +
	"\x06in_key\x18\x06 \x01(\tR\x05inKey\x12\x17\n" +
	"\aout_key\x18\a \x01(\tR\x06outKey\x12\x1b\n" +
	"\tis_hidden\x18\b \x01(\bR\bisHiddenB)Z'github.com/jjudge-oj/api/proto;jjudgepbb\x06proto3"

var (
	file_problem_proto_rawDescOnce sync.Once
	file_problem_proto_rawDescData []byte
)

func file_problem_proto_rawDescGZIP() []byte {
	file_problem_proto_rawDescOnce.Do(func() {
		file_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_problem_proto_rawDesc), len(file_problem_proto_rawDesc)))
	})
	return file_problem_proto_rawDescData
}

var file_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_problem_proto_goTypes = []any{
	(*Problem)(nil),               // 0: api.Problem
	(*TestcaseBundle)(nil),        // 1: api.TestcaseBundle
	(*TestcaseGroup)(nil),         // 2: api.TestcaseGroup
	(*Testcase)(nil),              // 3: api.Testcase
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_problem_proto_depIdxs = []int32{
	1, // 0: api.Problem.testcase_bundle:type_name -> api.TestcaseBundle
	4, // 1: api.Problem.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: api.Problem.updated_at:type_name -> google.protobuf.Timestamp
	2, // 3: api.TestcaseBundle.testcase_groups:type_name -> api.TestcaseGroup
	3, // 4: api.TestcaseGroup.testcases:type_name -> api.Testcase
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_problem_proto_init() }
func file_problem_proto_init() {
	if File_problem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_problem_proto_rawDesc), len(file_problem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_problem_proto_goTypes,
		DependencyIndexes: file_problem_proto_depIdxs,
		MessageInfos:      file_problem_proto_msgTypes,
	}.Build()
	File_problem_proto = out.File
	file_problem_proto_goTypes = nil
	file_problem_proto_depIdxs = nil
}
