// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: api/graderpb/grader.proto

package graderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Output         string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExpectedOutput string                 `protobuf:"bytes,2,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	UseGrader      string                 `protobuf:"bytes,3,opt,name=use_grader,json=useGrader,proto3" json:"use_grader,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GraderRequest) Reset() {
	*x = GraderRequest{}
	mi := &file_api_graderpb_grader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraderRequest) ProtoMessage() {}

func (x *GraderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_graderpb_grader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraderRequest.ProtoReflect.Descriptor instead.
func (*GraderRequest) Descriptor() ([]byte, []int) {
	return file_api_graderpb_grader_proto_rawDescGZIP(), []int{0}
}

func (x *GraderRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GraderRequest) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

func (x *GraderRequest) GetUseGrader() string {
	if x != nil {
		return x.UseGrader
	}
	return ""
}

type GraderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraderResponse) Reset() {
	*x = GraderResponse{}
	mi := &file_api_graderpb_grader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraderResponse) ProtoMessage() {}

func (x *GraderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_graderpb_grader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraderResponse.ProtoReflect.Descriptor instead.
func (*GraderResponse) Descriptor() ([]byte, []int) {
	return file_api_graderpb_grader_proto_rawDescGZIP(), []int{1}
}

func (x *GraderResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_graderpb_grader_proto protoreflect.FileDescriptor

const file_api_graderpb_grader_proto_rawDesc = "" +
	"\n" +
	"\x19api/graderpb/grader.proto\x12\bgraderpb\"o\n" +
	"\rGraderRequest\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12'\n" +
	"\x0fexpected_output\x18\x02 \x01(\tR\x0eexpectedOutput\x12\x1d\n" +
	"\n" +
	"use_grader\x18\x03 \x01(\tR\tuseGrader\" \n" +
	"\x0eGraderResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2D\n" +
	"\x06Grader\x12:\n" +
	"\x05Grade\x12\x17.graderpb.GraderRequest\x1a\x18.graderpb.GraderResponseB3Z1github.com/jjudge-oj/grader/api/graderpb;graderpbb\x06proto3"

var (
	file_api_graderpb_grader_proto_rawDescOnce sync.Once
	file_api_graderpb_grader_proto_rawDescData []byte
)

func file_api_graderpb_grader_proto_rawDescGZIP() []byte {
	file_api_graderpb_grader_proto_rawDescOnce.Do(func() {
		file_api_graderpb_grader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_graderpb_grader_proto_rawDesc), len(file_api_graderpb_grader_proto_rawDesc)))
	})
	return file_api_graderpb_grader_proto_rawDescData
}

var file_api_graderpb_grader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_graderpb_grader_proto_goTypes = []any{
	(*GraderRequest)(nil),  // 0: graderpb.GraderRequest
	(*GraderResponse)(nil), // 1: graderpb.GraderResponse
}
var file_api_graderpb_grader_proto_depIdxs = []int32{
	0, // 0: graderpb.Grader.Grade:input_type -> graderpb.GraderRequest
	1, // 1: graderpb.Grader.Grade:output_type -> graderpb.GraderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_graderpb_grader_proto_init() }
func file_api_graderpb_grader_proto_init() {
	if File_api_graderpb_grader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_graderpb_grader_proto_rawDesc), len(file_api_graderpb_grader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_graderpb_grader_proto_goTypes,
		DependencyIndexes: file_api_graderpb_grader_proto_depIdxs,
		MessageInfos:      file_api_graderpb_grader_proto_msgTypes,
	}.Build()
	File_api_graderpb_grader_proto = out.File
	file_api_graderpb_grader_proto_goTypes = nil
	file_api_graderpb_grader_proto_depIdxs = nil
}
