// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: submission.proto

package jjudgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdict int32

const (
	Verdict_VERDICT_PENDING               Verdict = 0
	Verdict_VERDICT_JUDGING               Verdict = 1
	Verdict_VERDICT_ACCEPTED              Verdict = 2
	Verdict_VERDICT_WRONG_ANSWER          Verdict = 3
	Verdict_VERDICT_TIME_LIMIT_EXCEEDED   Verdict = 4
	Verdict_VERDICT_MEMORY_LIMIT_EXCEEDED Verdict = 5
	Verdict_VERDICT_RUNTIME_ERROR         Verdict = 6
	Verdict_VERDICT_COMPILATION_ERROR     Verdict = 7
	Verdict_VERDICT_SYSTEM_ERROR          Verdict = 8
	Verdict_VERDICT_INTERNAL_ERROR        Verdict = 9
	Verdict_VERDICT_SKIPPED               Verdict = 10
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0:  "VERDICT_PENDING",
		1:  "VERDICT_JUDGING",
		2:  "VERDICT_ACCEPTED",
		3:  "VERDICT_WRONG_ANSWER",
		4:  "VERDICT_TIME_LIMIT_EXCEEDED",
		5:  "VERDICT_MEMORY_LIMIT_EXCEEDED",
		6:  "VERDICT_RUNTIME_ERROR",
		7:  "VERDICT_COMPILATION_ERROR",
		8:  "VERDICT_SYSTEM_ERROR",
		9:  "VERDICT_INTERNAL_ERROR",
		10: "VERDICT_SKIPPED",
	}
	Verdict_value = map[string]int32{
		"VERDICT_PENDING":               0,
		"VERDICT_JUDGING":               1,
		"VERDICT_ACCEPTED":              2,
		"VERDICT_WRONG_ANSWER":          3,
		"VERDICT_TIME_LIMIT_EXCEEDED":   4,
		"VERDICT_MEMORY_LIMIT_EXCEEDED": 5,
		"VERDICT_RUNTIME_ERROR":         6,
		"VERDICT_COMPILATION_ERROR":     7,
		"VERDICT_SYSTEM_ERROR":          8,
		"VERDICT_INTERNAL_ERROR":        9,
		"VERDICT_SKIPPED":               10,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_submission_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_submission_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{0}
}

type Submission struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProblemId       int64                  `protobuf:"varint,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	UserId          int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code            string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Language        string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Verdict         Verdict                `protobuf:"varint,6,opt,name=verdict,proto3,enum=api.Verdict" json:"verdict,omitempty"`
	Score           int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	CpuTime         int64                  `protobuf:"varint,8,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	Memory          int64                  `protobuf:"varint,9,opt,name=memory,proto3" json:"memory,omitempty"`
	Message         string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	TestsPassed     int32                  `protobuf:"varint,11,opt,name=tests_passed,json=testsPassed,proto3" json:"tests_passed,omitempty"`
	TestsTotal      int32                  `protobuf:"varint,12,opt,name=tests_total,json=testsTotal,proto3" json:"tests_total,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TestcaseResults []*TestcaseResult      `protobuf:"bytes,15,rep,name=testcase_results,json=testcaseResults,proto3" json:"testcase_results,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{0}
}

func (x *Submission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Submission) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *Submission) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Submission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Submission) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Submission) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_PENDING
}

func (x *Submission) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Submission) GetCpuTime() int64 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *Submission) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Submission) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Submission) GetTestsPassed() int32 {
	if x != nil {
		return x.TestsPassed
	}
	return 0
}

func (x *Submission) GetTestsTotal() int32 {
	if x != nil {
		return x.TestsTotal
	}
	return 0
}

func (x *Submission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Submission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Submission) GetTestcaseResults() []*TestcaseResult {
	if x != nil {
		return x.TestcaseResults
	}
	return nil
}

type SubmissionJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *Submission            `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	Problem       *Problem               `protobuf:"bytes,2,opt,name=problem,proto3" json:"problem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionJob) Reset() {
	*x = SubmissionJob{}
	mi := &file_submission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionJob) ProtoMessage() {}

func (x *SubmissionJob) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionJob.ProtoReflect.Descriptor instead.
func (*SubmissionJob) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{1}
}

func (x *SubmissionJob) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

func (x *SubmissionJob) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

type TestcaseResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   int64                  `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	TestcaseId     int64                  `protobuf:"varint,2,opt,name=testcase_id,json=testcaseId,proto3" json:"testcase_id,omitempty"`
	Verdict        Verdict                `protobuf:"varint,3,opt,name=verdict,proto3,enum=api.Verdict" json:"verdict,omitempty"`
	CpuTime        int64                  `protobuf:"varint,4,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	Memory         int64                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Input          *string                `protobuf:"bytes,6,opt,name=input,proto3,oneof" json:"input,omitempty"`
	ExpectedOutput *string                `protobuf:"bytes,7,opt,name=expected_output,json=expectedOutput,proto3,oneof" json:"expected_output,omitempty"`
	ActualOutput   *string                `protobuf:"bytes,8,opt,name=actual_output,json=actualOutput,proto3,oneof" json:"actual_output,omitempty"`
	ErrorMessage   *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestcaseResult) Reset() {
	*x = TestcaseResult{}
	mi := &file_submission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestcaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestcaseResult) ProtoMessage() {}

func (x *TestcaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_submission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestcaseResult.ProtoReflect.Descriptor instead.
func (*TestcaseResult) Descriptor() ([]byte, []int) {
	return file_submission_proto_rawDescGZIP(), []int{2}
}

func (x *TestcaseResult) GetSubmissionId() int64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *TestcaseResult) GetTestcaseId() int64 {
	if x != nil {
		return x.TestcaseId
	}
	return 0
}

func (x *TestcaseResult) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_PENDING
}

func (x *TestcaseResult) GetCpuTime() int64 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *TestcaseResult) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *TestcaseResult) GetInput() string {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return ""
}

func (x *TestcaseResult) GetExpectedOutput() string {
	if x != nil && x.ExpectedOutput != nil {
		return *x.ExpectedOutput
	}
	return ""
}

func (x *TestcaseResult) GetActualOutput() string {
	if x != nil && x.ActualOutput != nil {
		return *x.ActualOutput
	}
	return ""
}

func (x *TestcaseResult) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_submission_proto protoreflect.FileDescriptor

const file_submission_proto_rawDesc = "" +
	"\n" +
	"\x10submission.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rproblem.proto\"\x89\x04\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\x03R\tproblemId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12&\n" +
	"\averdict\x18\x06 \x01(\x0e2\f.api.VerdictR\averdict\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12\x19\n" +
	"\bcpu_time\x18\b \x01(\x03R\acpuTime\x12\x16\n" +
	"\x06memory\x18\t \x01(\x03R\x06memory\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\x12!\n" +
	"\ftests_passed\x18\v \x01(\x05R\vtestsPassed\x12\x1f\n" +
	"\vtests_total\x18\f \x01(\x05R\n" +
	"testsTotal\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\x10testcase_results\x18\x0f \x03(\v2\x13.api.TestcaseResultR\x0ftestcaseResults\"h\n" +
	"\rSubmissionJob\x12/\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x0f.api.SubmissionR\n" +
	"submission\x12&\n" +
	"\aproblem\x18\x02 \x01(\v2\f.api.ProblemR\aproblem\"\x90\x03\n" +
	"\x0eTestcaseResult\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\x03R\fsubmissionId\x12\x1f\n" +
	"\vtestcase_id\x18\x02 \x01(\x03R\n" +
	"testcaseId\x12&\n" +
	"\averdict\x18\x03 \x01(\x0e2\f.api.VerdictR\averdict\x12\x19\n" +
	"\bcpu_time\x18\x04 \x01(\x03R\acpuTime\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory\x12\x19\n" +
	"\x05input\x18\x06 \x01(\tH\x00R\x05input\x88\x01\x01\x12,\n" +
	"\x0fexpected_output\x18\a \x01(\tH\x01R\x0eexpectedOutput\x88\x01\x01\x12(\n" +
	"\ractual_output\x18\b \x01(\tH\x02R\factualOutput\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\t \x01(\tH\x03R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_inputB\x12\n" +
	"\x10_expected_outputB\x10\n" +
	"\x0e_actual_outputB\x10\n" +
	"\x0e_error_message*\xac\x02\n" +
	"\aVerdict\x12\x13\n" +
	"\x0fVERDICT_PENDING\x10\x00\x12\x13\n" +
	"\x0fVERDICT_JUDGING\x10\x01\x12\x14\n" +
	"\x10VERDICT_ACCEPTED\x10\x02\x12\x18\n" +
	"\x14VERDICT_WRONG_ANSWER\x10\x03\x12\x1f\n" +
	"\x1bVERDICT_TIME_LIMIT_EXCEEDED\x10\x04\x12!\n" +
	"\x1dVERDICT_MEMORY_LIMIT_EXCEEDED\x10\x05\x12\x19\n" +
	"\x15VERDICT_RUNTIME_ERROR\x10\x06\x12\x1d\n" +
	"\x19VERDICT_COMPILATION_ERROR\x10\a\x12\x18\n" +
	"\x14VERDICT_SYSTEM_ERROR\x10\b\x12\x1a\n" +
	"\x16VERDICT_INTERNAL_ERROR\x10\t\x12\x13\n" +
	"\x0fVERDICT_SKIPPED\x10\n" +
	"B)Z'github.com/jjudge-oj/api/proto;jjudgepbb\x06proto3"

var (
	file_submission_proto_rawDescOnce sync.Once
	file_submission_proto_rawDescData []byte
)

func file_submission_proto_rawDescGZIP() []byte {
	file_submission_proto_rawDescOnce.Do(func() {
		file_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_submission_proto_rawDesc), len(file_submission_proto_rawDesc)))
	})
	return file_submission_proto_rawDescData
}

var file_submission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_submission_proto_goTypes = []any{
	(Verdict)(0),                  // 0: api.Verdict
	(*Submission)(nil),            // 1: api.Submission
	(*SubmissionJob)(nil),         // 2: api.SubmissionJob
	(*TestcaseResult)(nil),        // 3: api.TestcaseResult
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Problem)(nil),               // 5: api.Problem
}
var file_submission_proto_depIdxs = []int32{
	0, // 0: api.Submission.verdict:type_name -> api.Verdict
	4, // 1: api.Submission.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: api.Submission.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: api.Submission.testcase_results:type_name -> api.TestcaseResult
	1, // 4: api.SubmissionJob.submission:type_name -> api.Submission
	5, // 5: api.SubmissionJob.problem:type_name -> api.Problem
	0, // 6: api.TestcaseResult.verdict:type_name -> api.Verdict
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_submission_proto_init() }
func file_submission_proto_init() {
	if File_submission_proto != nil {
		return
	}
	file_problem_proto_init()
	file_submission_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_submission_proto_rawDesc), len(file_submission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_submission_proto_goTypes,
		DependencyIndexes: file_submission_proto_depIdxs,
		EnumInfos:         file_submission_proto_enumTypes,
		MessageInfos:      file_submission_proto_msgTypes,
	}.Build()
	File_submission_proto = out.File
	file_submission_proto_goTypes = nil
	file_submission_proto_depIdxs = nil
}
