// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: api/graderpb/grader.proto

package graderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grader_Grade_FullMethodName = "/graderpb.Grader/Grade"
)

// GraderClient is the client API for Grader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraderClient interface {
	Grade(ctx context.Context, in *GraderRequest, opts ...grpc.CallOption) (*GraderResponse, error)
}

type graderClient struct {
	cc grpc.ClientConnInterface
}

func NewGraderClient(cc grpc.ClientConnInterface) GraderClient {
	return &graderClient{cc}
}

func (c *graderClient) Grade(ctx context.Context, in *GraderRequest, opts ...grpc.CallOption) (*GraderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraderResponse)
	err := c.cc.Invoke(ctx, Grader_Grade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraderServer is the server API for Grader service.
// All implementations must embed UnimplementedGraderServer
// for forward compatibility.
type GraderServer interface {
	Grade(context.Context, *GraderRequest) (*GraderResponse, error)
	mustEmbedUnimplementedGraderServer()
}

// UnimplementedGraderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraderServer struct{}

func (UnimplementedGraderServer) Grade(context.Context, *GraderRequest) (*GraderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Grade not implemented")
}
func (UnimplementedGraderServer) mustEmbedUnimplementedGraderServer() {}
func (UnimplementedGraderServer) testEmbeddedByValue()                {}

// UnsafeGraderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraderServer will
// result in compilation errors.
type UnsafeGraderServer interface {
	mustEmbedUnimplementedGraderServer()
}

func RegisterGraderServer(s grpc.ServiceRegistrar, srv GraderServer) {
	// If the following call panics, it indicates UnimplementedGraderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grader_ServiceDesc, srv)
}

func _Grader_Grade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServer).Grade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grader_Grade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServer).Grade(ctx, req.(*GraderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grader_ServiceDesc is the grpc.ServiceDesc for Grader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graderpb.Grader",
	HandlerType: (*GraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Grade",
			Handler:    _Grader_Grade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/graderpb/grader.proto",
}
